use mydb;

insert into specialites
    (nom,nbr_sousSpecialite,nbr_followers,nbr_document)
values
    ('Géographie et Aménagement du Territoire', 3, 0, 9),
    ('Math', 4, 0, 12),
    ('Informatique', 3, 0, 9),
    ('Physique', 3, 0, 9),
    ('Génie Mécanique', 3, 0, 9),
    ('Génie des Procédés', 2, 0, 6),
    ('Génie Civil', 2, 0, 6),
    ('Hydraulique', 1, 0, 3),
    ('Electronique Electrotechnique', 3, 0, 9),
    ('Géophysique', 1, 0, 3),
    ('Chimie', 4, 0, 12);


insert into sous_specialites
    (id_specialite,nom,nbr_document,nbr_Followers,Image_SS)
values(1, 'Géomorphologie et Protection de l’Environnement', 3, 0,"/public/uploads/specialite1.jpg"),
    (1, 'Géomatique', 3, 0,"/public/uploads/specialite2.jpg"),
    (1, 'Climat- Environnement', 3, 0,"/public/uploads/specialite3.jpg"),
    (2, "algèbre et cryptographie", 3, 0,"/public/uploads/specialite4.jpg"),
    (2, "Mathématiques", 3, 0,"/public/uploads/specialite5.jpg"),
    (2, "Ingénierie Statistique", 3, 0,"/public/uploads/specialite6.jpg"),
    (2, "Recherche Opérationnelle", 3, 0,"/public/uploads/specialite7.jpg"),
    (3, "Informatique académique", 3, 0,"/public/uploads/specialite8.jpg"),
    (3, "Ingénierie des Systèmes d’Information et des Logiciels", 3, 0,"/public/uploads/specialite9.jpg"),
    (3, "Génie des Télécommunications et Réseaux", 3, 0,"/public/uploads/specialite10.jpg"),
    (4, "Physique", 3, 0,"/public/uploads/specialite11.jpg"),
    (4, "Electricité", 3, 0,"/public/uploads/specialite12.jpg"),
    (4, "Energétique", 3, 0,"/public/uploads/specialite13.jpg"),
    (5, "Construction Mécaniques", 3, 0,"/public/uploads/specialite14.jpg"),
    (5, "Génie des Matériaux ", 3, 0,"/public/uploads/specialite15.jpg"),
    (5, "Energétique", 3, 0,"/public/uploads/specialite13.jpg"),
    (6, "Raffinage et Pétrochimie", 3, 0,"/public/uploads/specialite17.jpg"),
    (6, "Génie des Procédés", 3, 0,"/public/uploads/specialite18.jpg"),
    (7, "Génie Civil", 3, 0,"/public/uploads/specialite19.jpg"),
    (7, "Génie Civil Appliquée", 3, 0,"/public/uploads/specialite19.jpg"),
    (8, "Hydraulique", 3, 0,"/public/uploads/specialite21.jpg"),
    (9, "Génie Electrique", 3, 0,"/public/uploads/specialite22.jpg"),
    (9, "Génie Electrique et Génie des Systèmes", 3, 0,"/public/uploads/specialite22.jpg"),
    (9, "Licence de Télécommunications", 3, 0,"/public/uploads/specialite24.jpg"),
    (10, "Géophysique", 3, 0,"/public/uploads/specialite25.jpg"),
    (11, "Chimie Fondamentale", 3, 0,"/public/uploads/specialite26.jpg"),
    (11, "Chimie du médicament", 3, 0,"/public/uploads/specialite26.jpg"),
    (11, "Chimie de l'environnement", 3, 0,"/public/uploads/specialite26.jpg"),
    (11, "Chimie des Matériaux", 3, 0,"/public/uploads/specialite29.jpg");





insert into document
    (id_sous_specialite,titre,description,nbr_like,nbr_commentaire,nbr_views,nbr_quizz,doc_path,video_path,audio_path,Date)
values(1, "Les précurseurs", "Une description du cours explique aux participants potentiels les points abordés dans votre cours. Il contribue grandement à les convaincre que votre cours, et votre cours seulement", 0, 0, 0, 4,"/public/Documents/doc1.pdf","/public/Video/doc1.mp4","/public/Audio/doc1.m4a" , curdate()),
    (1, "L’actualisme", "La géomorphologie est la science qui étudie les formes de relief, les formations associées, leur évolution, les mécanismes – d’origine interne ou externe – qui les façonnent et les facteurs qui les contrôlent. ", 0, 0, 0, 1,"/public/Documents/doc1.pdf","/public/Video/doc1.mp4",null, curdate()),
    (1, "Les systèmes en géomorphologie", "La revue trimestrielle Géomorphologie : Relief, Processus, Environnement accueille des contributions portant sur la géomorphologie dans l’acception la plus large : formes du relief à toutes les échelles, modelés, processus de toutes natures.", 0, 0, 0, 1,null,null,null, curdate()),
    (2, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (2, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (2, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (3, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (3, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (3, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (4, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (4, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (4, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (5, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (5, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (5, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (6, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (6, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (6, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (7, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (7, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 1,null,null,null, curdate()),
    (7, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (8, "la complexité", "complexité d'un algorithme la complexité d'un algorithme est le nombre d'opérations élémentaires qu'il doit effectuer pour mener à bien un calcul en fonction de la taille des données d'entrée. complexité d'un problème la complexité d'un problème A est la complexité du meilleur algorithme qui résout A ", 0, 0, 0, 0,null,"/public/Video/doc1.mp4",null, curdate()),
    (8, "L’algorithmique", "L’algorithmique est un terme d’origine arabe, comme algèbre, amiral ou zénith. Ce n’est pas une excuse pour massacrer son orthographe, ou sa prononciation.
Ainsi, l’algo n’est pas « rythmique », à la différence du bon rock’n roll. L’algo n’est pas non plus « l’agglo ».
Alors, ne confondez pas l’algorithmique avec l’agglo rythmique, qui consiste à poser des parpaings en cadence.", 0, 0, 0, 0,"/public/Documents/doc1.pdf",null,"/public/Audio/doc1.m4a", curdate()),
    (8, "Arbre binaire", "En informatique, un arbre binaire est une structure de données qui peut se représenter sous la forme d'une hiérarchie dont chaque élément est appelé nœud, le nœud initial étant appelé racine.", 0, 0, 0, 0,null,null,null, curdate()),
    (9, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (9, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (9, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (10, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (10, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (10, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (11, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (11, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (11, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (12, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (12, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (12, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (13, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (13, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (13, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (14, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (14, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (14, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.",0, 0, 0, 0,null,null,null, curdate()),
    (15, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (15, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (15, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (16, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 90, 0, 0, 0,null,null,null, curdate()),
    (16, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (16, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (17, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (17, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (17, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (18, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (18, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (18, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (19, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (19, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (19, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (20, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (20, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (20, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (21, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (21, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (21, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (22, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (22, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (22, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (23, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (23, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (23, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (24, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (24, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (24, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (25, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (25, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (25, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (26, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (26, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (26, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (27, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (27, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (27, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (28, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (28, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (28, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (29, "Document 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (29, "Document 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate()),
    (29, "Document 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare. Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros.", 0, 0, 0, 0,null,null,null, curdate());


insert into quizz
    (id_document,nom_quiz)
VALUES(23, 'Les boucles'),
    (1, 'Quizz 2'),
    (1, 'Quizz 3'),
    (1, 'Quizz 4'),
    (2, 'Quizz 5'),
    (3, 'Quizz 7'),
    (4, 'Quizz 9'),
    (5, 'Quizz 12'),
    (6, 'Quizz 13'),
    (7, 'Quizz 10'),
    (8, 'Quizz 123'),
    (8, 'Quizz 2AS'),
    (9, 'Quizz 3'),
    (10, 'Quizz 56'),
    (11, 'Quizz 09'),
    (12, 'Quizz 203'),
    (13, 'Quizz 23'),
    (14, 'Quizz 54'),
    (15, 'Quizz 21'),
    (16, 'Quizz 2'),
    (17, 'Quizz 293'),
    (18, 'Quizz 34'),
    (19, 'Quizz 923'),
    (20, 'Quizz 534');


insert into question
    (id_quiz,question_text,reponse_1,reponse_2,reponse_3,reponse_4,juste_reponse)
values(1, "un nombre flottant", "est toujours positif", "est toujours inférieur à 0", "peut avoir une décimale",null, 3),
    (1, "le ET logique retourne vrai si", "si les deux opérandes sont vrais", "si l'un des opérandes est vrai, mais pas les deux", "si un seul des opérandes est vrai", null, 3),
    (1, "Le résultat d'une instruction de condition est toujours", "une valeur de chaîne de caractère", "une valeur booléenne", "une valeur numérique", null, 2),
    (1, "la boucle 'for' classique comprend combien de composants?", "1", "4", "3", "2", 3),
    (2, "Vestibulum hendrerit vehicula consectetur", "reponse 9", "reponse 5", "reponse 9", null, 1),
    (2, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", "reponse 3", "reponse 9", "reponse 10", 4),
    (2, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 3),
    (2, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 1),
    (2, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 2),
    (2, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", "reponse 9", "reponse 3", null, "reponse 10", 2),
    (2, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", null, "reponse 10", 1),
    (2, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (2, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", null, "reponse 3", "reponse 4", "reponse 10", 4),
    (2, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", null, null, "reponse 10", 1),
    (2, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", null, null, "reponse 10", 4),
    (3, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque.", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (3, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (3, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 3),
    (3, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 2),
    (3, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", null, "reponse 3", "reponse 4", "reponse 10", 4),
    (3, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", null, "reponse 4", "reponse 10", 4),
    (3, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 2),
    (3, "Nullam vulputate ipsum sit amet risus cursus", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (3, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", null, "reponse 3", "reponse 4", "reponse 10", 2),
    (3, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque", "reponse 9", null, null, "reponse 10", 1),
    (3, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", null, null, "reponse 10", 4),
    (4, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", "reponse 1", "reponse 4", "reponse 2", "reponse 3", 1),
    (4, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 3),
    (4, "In tincidunt ac libero at condimentum. Nullam ultrices turpis sed sapien convallis semper. Praesent quis nulla volutpat", "reponse 2", "reponse 3", "reponse 4", "reponse 10", 3),
    (4, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque", "reponse 2", "reponse 5", "reponse 4", null, 2),
    (4, "Vestibulum hendrerit vehicula consectetur", "reponse 9", "reponse 5", "reponse 9", null, 1),
    (4, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", "reponse 3", "reponse 9", "reponse 10", 4),
    (4, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 3),
    (4, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 1),
    (5, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 2),
    (5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", "reponse 9", "reponse 3", null, "reponse 10", 2),
    (5, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", null, "reponse 10", 1),
    (5, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", null, "reponse 3", "reponse 4", "reponse 10", 4),
    (5, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", null, null, "reponse 10", 1),
    (5, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", null, null, "reponse 10", 4),
    (6, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque.", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (6, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (6, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 3),
    (6, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 2),
    (6, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", null, "reponse 3", "reponse 4", "reponse 10", 4),
    (6, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", null, "reponse 4", "reponse 10", 4),
    (6, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 2),
    (6, "Nullam vulputate ipsum sit amet risus cursus", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (6, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", null, "reponse 3", "reponse 4", "reponse 10", 2),
    (6, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque", "reponse 9", null, null, "reponse 10", 1),
    (6, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", null, null, "reponse 10", 4),
    (7, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", "reponse 1", "reponse 4", "reponse 2", "reponse 3", 1),
    (7, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 3),
    (7, "In tincidunt ac libero at condimentum. Nullam ultrices turpis sed sapien convallis semper. Praesent quis nulla volutpat", "reponse 2", "reponse 3", "reponse 4", "reponse 10", 3),
    (7, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque", "reponse 2", "reponse 5", "reponse 4", null, 2),
    (8, "Vestibulum hendrerit vehicula consectetur", "reponse 9", "reponse 5", "reponse 9", null, 1),
    (8, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", "reponse 3", "reponse 9", "reponse 10", 4),
    (8, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 3),
    (8, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 1),
    (8, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 2),
    (8, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", "reponse 9", "reponse 3", null, "reponse 10", 2),
    (9, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", null, "reponse 10", 1),
    (9, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (9, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", null, "reponse 3", "reponse 4", "reponse 10", 4),
    (9, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", null, null, "reponse 10", 1),
    (9, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", null, null, "reponse 10", 4),
    (9, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque.", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (9, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (9, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 3),
    (9, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 2),
    (9, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", null, "reponse 3", "reponse 4", "reponse 10", 4),
    (10, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", null, "reponse 4", "reponse 10", 4),
    (10, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 2),
    (10, "Nullam vulputate ipsum sit amet risus cursus", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (10, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", null, "reponse 3", "reponse 4", "reponse 10", 2),
    (11, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque", "reponse 9", null, null, "reponse 10", 1),
    (11, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", null, null, "reponse 10", 4),
    (12, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", "reponse 1", "reponse 4", "reponse 2", "reponse 3", 1),
    (12, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 3),
    (12, "In tincidunt ac libero at condimentum. Nullam ultrices turpis sed sapien convallis semper. Praesent quis nulla volutpat", "reponse 2", "reponse 3", "reponse 4", "reponse 10", 3),
    (12, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque", "reponse 2", "reponse 5", "reponse 4", null, 2),
    (12, "Vestibulum hendrerit vehicula consectetur", "reponse 9", "reponse 5", "reponse 9", null, 1),
    (12, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", "reponse 3", "reponse 9", "reponse 10", 4),
    (13, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 3),
    (13, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 1),
    (13, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 2),
    (13, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", "reponse 9", "reponse 3", null, "reponse 10", 2),
    (13, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", null, "reponse 10", 1),
    (13, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (13, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", null, "reponse 3", "reponse 4", "reponse 10", 4),
    (13, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", null, null, "reponse 10", 1),
    (13, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", null, null, "reponse 10", 4),
    (13, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque.", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (14, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (14, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 3),
    (14, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 2),
    (14, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", null, "reponse 3", "reponse 4", "reponse 10", 4),
    (14, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", null, "reponse 4", "reponse 10", 4),
    (15, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 2),
    (15, "Nullam vulputate ipsum sit amet risus cursus", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (15, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", null, "reponse 3", "reponse 4", "reponse 10", 2),
    (15, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque", "reponse 9", null, null, "reponse 10", 1),
    (15, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", null, null, "reponse 10", 4),
    (16, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", "reponse 1", "reponse 4", "reponse 2", "reponse 3", 1),
    (16, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 3),
    (16, "In tincidunt ac libero at condimentum. Nullam ultrices turpis sed sapien convallis semper. Praesent quis nulla volutpat", "reponse 2", "reponse 3", "reponse 4", "reponse 10", 3),
    (16, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque", "reponse 2", "reponse 5", "reponse 4", null, 2),
    (16, "Vestibulum hendrerit vehicula consectetur", "reponse 9", "reponse 5", "reponse 9", null, 1),
    (16, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", "reponse 3", "reponse 9", "reponse 10", 4),
    (16, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 3),
    (16, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 1),
    (16, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 2),
    (16, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", "reponse 9", "reponse 3", null, "reponse 10", 2),
    (17, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", null, "reponse 10", 1),
    (17, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (17, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", null, "reponse 3", "reponse 4", "reponse 10", 4),
    (17, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", null, null, "reponse 10", 1),
    (18, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", null, null, "reponse 10", 4),
    (18, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque.", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (18, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (18, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 3),
    (19, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 2),
    (19, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", null, "reponse 3", "reponse 4", "reponse 10", 4),
    (19, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", null, "reponse 4", "reponse 10", 4),
    (19, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 2),
    (20, "Nullam vulputate ipsum sit amet risus cursus", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (20, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", null, "reponse 3", "reponse 4", "reponse 10", 2),
    (20, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque", "reponse 9", null, null, "reponse 10", 1),
    (20, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", null, null, "reponse 10", 4),
    (21, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", "reponse 1", "reponse 4", "reponse 2", "reponse 3", 1),
    (21, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 3),
    (21, "In tincidunt ac libero at condimentum. Nullam ultrices turpis sed sapien convallis semper. Praesent quis nulla volutpat", "reponse 2", "reponse 3", "reponse 4", "reponse 10", 3),
    (21, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque", "reponse 2", "reponse 5", "reponse 4", null, 2),
    (21, "Vestibulum hendrerit vehicula consectetur", "reponse 9", "reponse 5", "reponse 9", null, 1),
    (21, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", "reponse 3", "reponse 9", "reponse 10", 4),
    (21, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 3),
    (21, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 1),
    (22, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", "reponse 19", "reponse 4", "reponse 10", 2),
    (22, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", "reponse 9", "reponse 3", null, "reponse 10", 2),
    (22, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", null, "reponse 10", 1),
    (22, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (22, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis fringilla, lacinia orci ut, scelerisque neque. Praesent volutpat nisl non vestibulum ornare", null, "reponse 3", "reponse 4", "reponse 10", 4),
    (22, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", null, null, "reponse 10", 1),
    (22, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", "reponse 9", null, null, "reponse 10", 4),
    (23, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque.", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (23, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (23, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 3),
    (23, "Nullam ante est, tempus rhoncus lacinia et Nam pellentesque posuere nisi, eleifend lacinia lectus. Morbi id nisl quam", null, "reponse 3", "reponse 4", "reponse 10", 2),
    (23, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", null, "reponse 3", "reponse 4", "reponse 10", 4),
    (23, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", null, "reponse 4", "reponse 10", 4),
    (23, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", "reponse 9", "reponse 3", "reponse 4", "reponse 10", 2),
    (23, "Nullam vulputate ipsum sit amet risus cursus", null, "reponse 3", "reponse 4", "reponse 10", 3),
    (23, "Nullam ante est, tempus rhoncus lacinia et, dapibus quis eros. Fusce ut consequat sapien, eget malesuada risus. Quisque eget condimentum ex.", null, "reponse 3", "reponse 4", "reponse 10", 2),
    (23, "Vestibulum ligula neque, viverra non fermentum in, congue et massa. Vivamus eu tincidunt dui. Praesent vitae tellus sed libero vehicula scelerisque", "reponse 9", null, null, "reponse 10", 1),
    (23, "Nullam vulputate ipsum sit amet risus cursus", "reponse 9", null, null, "reponse 10", 4);
