-- MySQL Script generated by MySQL Workbench
-- 16 أوت, 2020 CET 08:08:50 م
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`BannedWord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BannedWord` (
  `id_word` INT NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_word`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`specialites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`specialites` (
  `id_specialite` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NULL DEFAULT NULL,
  `nbr_sousSpecialite` INT NULL DEFAULT '0',
  `nbr_followers` INT NULL DEFAULT '0',
  `nbr_document` INT NULL DEFAULT '0',
  PRIMARY KEY (`id_specialite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`sous_specialites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sous_specialites` (
  `id_sous_specialite` INT NOT NULL AUTO_INCREMENT,
  `id_specialite` INT NULL DEFAULT NULL,
  `nom` VARCHAR(200) NULL DEFAULT NULL,
  `nbr_document` INT NULL DEFAULT '0',
  `nbr_Followers` INT NULL DEFAULT '0',
  `Image_SS` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sous_specialite`),
  INDEX `id_specialite` (`id_specialite` ASC) VISIBLE,
  CONSTRAINT `sous_specialites_ibfk_1`
    FOREIGN KEY (`id_specialite`)
    REFERENCES `mydb`.`specialites` (`id_specialite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`document` (
  `id_document` INT NOT NULL AUTO_INCREMENT,
  `id_sous_specialite` INT NULL DEFAULT NULL,
  `titre` VARCHAR(30) NULL DEFAULT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  `nbr_like` INT NULL DEFAULT '0',
  `nbr_commentaire` INT NULL DEFAULT '0',
  `nbr_views` INT NULL DEFAULT '0',
  `nbr_quizz` INT NULL DEFAULT '0',
  `doc_path` VARCHAR(200) NULL DEFAULT NULL,
  `Date` date default null,
  PRIMARY KEY (`id_document`),
  INDEX `id_sous_specialite` (`id_sous_specialite` ASC) VISIBLE,
  CONSTRAINT `document_ibfk_1`
    FOREIGN KEY (`id_sous_specialite`)
    REFERENCES `mydb`.`sous_specialites` (`id_sous_specialite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`quizz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quizz` (
  `id_quiz` INT NOT NULL AUTO_INCREMENT,
  `id_document` INT NOT NULL,
  `nom_quiz` VARCHAR(255) NULL DEFAULT NULL,
  `rate` DECIMAL(2,1) NULL DEFAULT NULL,
  `number_of_rating` int default 0,
  PRIMARY KEY (`id_quiz`),
  INDEX `quiz_ibfk_1` (`id_document` ASC) VISIBLE,
  CONSTRAINT `quiz_ibfk_1`
    FOREIGN KEY (`id_document`)
    REFERENCES `mydb`.`document` (`id_document`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(255) NULL DEFAULT NULL,
  `SecondName` VARCHAR(255) NULL DEFAULT NULL,
  `Sex` VARCHAR(30) NULL DEFAULT NULL,
  `Photo` VARCHAR(255) NULL DEFAULT NULL,
  `insert_date` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Rates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rates` (
  `id_quiz` INT NOT NULL,
  `id_user` INT NOT NULL,
  `rate` DECIMAL(2,1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_quiz`),
  INDEX `rate_users_fk` (`id_user` ASC) VISIBLE,
  CONSTRAINT `rate_quizz_fk`
    FOREIGN KEY (`id_quiz`)
    REFERENCES `mydb`.`quizz` (`id_quiz`),
  CONSTRAINT `rate_users_fk`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`UserFollowedSSpecialite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserFollowedSSpecialite` (
  `id_sous_specialite` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_sous_specialite`, `id_user`),
  INDEX `user_fk` (`id_user` ASC) VISIBLE,
  CONSTRAINT `sspecialite_fk`
    FOREIGN KEY (`id_sous_specialite`)
    REFERENCES `mydb`.`sous_specialites` (`id_sous_specialite`),
  CONSTRAINT `user_fk`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`UserLikedDocument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserLikedDocument` (
  `id_document` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_document`, `id_user`),
  INDEX `documentliked_user_fk` (`id_user` ASC) VISIBLE,
  CONSTRAINT `documentliked_fk`
    FOREIGN KEY (`id_document`)
    REFERENCES `mydb`.`document` (`id_document`),
  CONSTRAINT `documentliked_user_fk`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`reponses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reponses` (
  `id_reponse` INT NOT NULL AUTO_INCREMENT,
  `auteur` INT NULL DEFAULT NULL,
  `contenu` VARCHAR(100) NULL DEFAULT NULL,
  `id_precedent` INT NULL DEFAULT NULL,
  `HaveAnswer` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_reponse`),
  INDEX `id_precedent` (`id_precedent` ASC) VISIBLE,
  INDEX `auteur` (`auteur` ASC) VISIBLE,
  CONSTRAINT `reponses_ibfk_1`
    FOREIGN KEY (`id_precedent`)
    REFERENCES `mydb`.`reponses` (`id_reponse`),
  CONSTRAINT `reponses_ibfk_2`
    FOREIGN KEY (`auteur`)
    REFERENCES `mydb`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commentaires` (
  `id_commentaire` INT NOT NULL,
  `id_document` INT NOT NULL,
  PRIMARY KEY (`id_commentaire`, `id_document`),
  INDEX `id_document` (`id_document` ASC) VISIBLE,
  CONSTRAINT `commentaires_ibfk_1`
    FOREIGN KEY (`id_commentaire`)
    REFERENCES `mydb`.`reponses` (`id_reponse`),
  CONSTRAINT `commentaires_ibfk_2`
    FOREIGN KEY (`id_document`)
    REFERENCES `mydb`.`document` (`id_document`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`UserNotification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserNotification` (
  `id_notification` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_document` INT DEFAULT NULL,
  `id_commentaire` INT DEFAULT NULL,
  `Seen` TINYINT(1) NULL DEFAULT '0',
  `title_doc` VARCHAR(100) NULL DEFAULT NULL,
  `title_SS` VARCHAR(100) NULL DEFAULT NULL,
  

  PRIMARY KEY (`id_notification`),
  INDEX `notification_document_fk` (`id_document` ASC) VISIBLE,
  INDEX `notification_commentaire_fk` (`id_commentaire` ASC) VISIBLE,
  INDEX `notification_user_fk` (`id_user` ASC) VISIBLE,
  CONSTRAINT `notification_commentaire_fk`
    FOREIGN KEY (`id_commentaire`)
    REFERENCES `mydb`.`reponses` (`id_reponse`),
  CONSTRAINT `notification_document_fk`
    FOREIGN KEY (`id_document`)
    REFERENCES `mydb`.`document` (`id_document`),
  CONSTRAINT `notification_user_fk`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`UserSavedDocument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserSavedDocument` (
  `id_document` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_document`, `id_user`),
  INDEX `document_user_fk` (`id_user` ASC) VISIBLE,
  CONSTRAINT `document_fk`
    FOREIGN KEY (`id_document`)
    REFERENCES `mydb`.`document` (`id_document`),
  CONSTRAINT `document_user_fk`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`feedBacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`feedBacks` (
  `id_feedBack` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `message` VARCHAR(2000) NULL DEFAULT NULL,
  `statu` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_feedBack`),
  INDEX `feedback_user_fk` (`id_user` ASC) VISIBLE,
  CONSTRAINT `feedback_user_fk`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`mark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mark` (
  `id_mark` INT NOT NULL AUTO_INCREMENT,
  `id_quiz` INT NOT NULL,
  `id_user` INT NOT NULL,
  `mark` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_mark`),
  UNIQUE INDEX `UQ_UserId_quizzID` (`id_quiz` ASC, `id_user` ASC) VISIBLE,
  INDEX `mark_ibfk_2` (`id_user` ASC) VISIBLE,
  CONSTRAINT `mark_ibfk_1`
    FOREIGN KEY (`id_quiz`)
    REFERENCES `mydb`.`quizz` (`id_quiz`),
  CONSTRAINT `mark_ibfk_2`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `id_question` INT NOT NULL AUTO_INCREMENT,
  `id_quiz` INT NOT NULL,
  `question_text` VARCHAR(300) NOT NULL,
  `reponse_1` VARCHAR(70) NULL DEFAULT NULL,
  `reponse_2` VARCHAR(70) NULL DEFAULT NULL,
  `reponse_3` VARCHAR(70) NULL DEFAULT NULL,
  `reponse_4` VARCHAR(70) NULL DEFAULT NULL,
  `juste_reponse` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_question`),
  INDEX `question_ibfk_1` (`id_quiz` ASC) VISIBLE,
  CONSTRAINT `question_ibfk_1`
    FOREIGN KEY (`id_quiz`)
    REFERENCES `mydb`.`quizz` (`id_quiz`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
